name: my_money_control
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  animate_do: ^1.6.3
  cupertino_icons: ^0.1.2
  flutter_masked_text: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/empty_transactions.png

  fonts:
  - family: ComicNeue
    fonts:
      - asset: assets/fonts/comic_neue/ComicNeue-Regular.ttf
      - asset: assets/fonts/comic_neue/ComicNeue-Bold.ttf
        weight: 700
      - asset: assets/fonts/comic_neue/ComicNeue-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/comic_neue/ComicNeue-Italic.ttf
        style: italic
  - family: Quicksand
    fonts:
      - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
      - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
        weight: 700