name: meal_algorithms
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^2.0.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
  - family: ComicNeue
    fonts:
      - asset: assets/fonts/comic_neue/ComicNeue-Regular.ttf
      - asset: assets/fonts/comic_neue/ComicNeue-Bold.ttf
        weight: 700
      - asset: assets/fonts/comic_neue/ComicNeue-BoldItalic.ttf
        weight: 700
        style: italic
      - asset: assets/fonts/comic_neue/ComicNeue-Italic.ttf
        style: italic
  - family: Quicksand
    fonts:
      - asset: assets/fonts/quicksand/Quicksand-Regular.ttf
      - asset: assets/fonts/quicksand/Quicksand-Bold.ttf
        weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
